Repository xmidt-org/ancla, pull requests merged in 2024-07, with the labels that each got.

#230 Argus package move
  .reuse/dep5
  chrysom/README.md
  chrysom/basicClient.go
  chrysom/basicClient_test.go
  chrysom/doc.go
  chrysom/listenerClient.go
  chrysom/listenerClient_test.go
  chrysom/metrics.go
  chrysom/pushResult.go
  chrysom/store.go
  go.mod
  go.sum
  internalWebhook.go
  internalWebhook_test.go
  metrics.go
  mocks_test.go
  model/model.go
  service.go
  service_test.go
Labels: dependencies

#232 missed one instance of argus/store
  go.mod
  go.sum
  transport_test.go
Labels: dependencies

#231 patch: func addWebhookRequestDecoder is missing returns
  transport.go
Labels: bug

#226 Set webhook defaults update
  transport.go
  transport_test.go
Labels: needs discussion

#229 Options draft
  go.mod
  go.sum
  webhookValidationConfig.go
  webhookValidationConfig_test.go
Labels: needs discussion

#235 Webhook validation config tests
  endpoint_test.go
  go.mod
  go.sum
  internalWebhook.go
  internalWebhook_test.go
  mocks_test.go
  transport.go
  transport_test.go
  watch_test.go
  webhookValidationConfig_test.go
Labels: enhancement
